// Generates the production CSP from the provider registry (§2.8): the
// connect-src allowlist is DERIVED from src/adapters/llm/providers.ts, so
// registering a provider is the one and only way to authorize its origin.
// Output: app/csp.caddy — imported by docker/Caddyfile inside its header block.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { buildCsp } from "../src/adapters/llm/csp";
import { PROVIDERS } from "../src/adapters/llm/providers";

const csp = buildCsp(PROVIDERS);
const out = fileURLToPath(new URL("../csp.caddy", import.meta.url));
writeFileSync(
  out,
  `# GENERATED by app/scripts/generate-csp.ts — do not edit by hand.\n` +
    `Content-Security-Policy "${csp}"\n`,
);
console.log(`csp.caddy written: ${csp.split("; ").find((d) => d.startsWith("connect-src")) ?? ""}`);
