// Generates the production CSP from the provider registry (§2.8): the
// connect-src allowlist is DERIVED from src/adapters/llm/providers.ts, so
// registering a provider is the one and only way to authorize its origin.
// Output: app/csp.caddy — imported by docker/Caddyfile inside its header block.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { PROVIDERS } from "../src/adapters/llm/providers.ts";

const providerOrigins = [...new Set(PROVIDERS.flatMap((p) => p.cspOrigins))];

const csp = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self'",
  "img-src 'self' data:",
  `connect-src 'self' ${providerOrigins.join(" ")}`,
  "base-uri 'none'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
].join("; ");

const out = fileURLToPath(new URL("../csp.caddy", import.meta.url));
writeFileSync(
  out,
  `# GENERATED by app/scripts/generate-csp.mjs — do not edit by hand.\n` +
    `Content-Security-Policy "${csp}"\n`,
);
console.log(`csp.caddy written: connect-src 'self' ${providerOrigins.join(" ")}`);